### PR TITLE
Cleanup, enhancement and fixing stuff PR

### LINKED ISSUE #5: Cleanup, enhancement and fixing stuff
Debloating the repo by removing unnecessary stuff, this will make the repo more organized. Also make some further enhancements. Changes will be made on the [`cleanup`](https://github.com/yell0wsuit/iWriter/tree/cleanup) branch.

Things to do (ticked means done):
- [x] Removing unused or outdated files.
- [x] Removing unused lines in HTML files.
- [x] Removing unused classes in the `style.css` file.
- [x] Removing unused code/functions in the `controller.js` file.
- [x] Removing unused code/functions in the `custom.js` file.
- [x] Fixing remaining bugs.
- [x] Utilize Bootstrap 5 framework.

**IMPORTANT:** make sure there's no regression due to these changes (sometimes removing wrong stuff cause thing to break)

### PR DESCRIPTION
**Pull request by yell0wsuit**
See issue #5.

### CODE REVIEW

**Review by yell0wsuit — COMMENTED** [review]
.

File: scripts/controller.js [hunk 1]
```diff
@@ -2498,7 +2498,7 @@ addEventListener("DOMContentLoaded", (event) => {
 
 $(function () {
     $('body').popover({
-        selector: '[data-bs-toggle=popover]',
-        trigger: 'focus'
+        selector: '[data-bs-toggle="popover"]',
+        trigger: 'hover focus'
```
Comment (yell0wsuit) [inline scripts/controller.js:1923]: And it works on touch screen now
